services:
  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      SERVER_PORT: 8761

    healthcheck:
      #Ejecutar para instalar Curl y ver el estado del MS o servidor
      test: ["CMD-SHELL","curl -f http://localhost:8761/actuator/health || exit 1"]

      #Cada cuanto tiempo voy a comprobar la salud
      interval: 10s

      #Cuanto esperar para decir que fallo
      timeout: 5s

      #Cuantas veces reintento
      retries: 10

    restart: unless-stopped

  ms-productos:
    build: ./ms-productos
    container_name: ms-productos
    ports:
       - "8081:8081"
    environment:
      SERVER_PORT: 8081

      #Direccion del servidor de EUREKA
      EUREKA_URL: http://eureka-server:8761/eureka
    depends_on:
      eureka-server:
        #Eureka va a esperar que el MS este sanito
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL","curl -f http://localhost:8761/actuator/health || exit 1"]
      interval: 10s

      #Cuanto esperar para decir que fallo
      timeout: 5s

      #Cuantas veces reintento
      retries: 10

    restart: unless-stopped


  ms-pedidos:
    build: ./ms-pedidos
    container_name: ms-pedidos
    ports:
      - "8082:8082"
    environment:
      SERVER_PORT: 8082

      #Direccion del servidor de EUREKA
      EUREKA_URL: http://eureka-server:8761/eureka
    depends_on:
      eureka-server:
        #Eureka va a esperar que el MS este sanito
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL","curl -f http://localhost:8761/actuator/health || exit 1" ]
      interval: 10s

      #Cuanto esperar para decir que fallo
      timeout: 5s

      #Cuantas veces reintento
      retries: 10

    restart: unless-stopped







